[tool.poetry]
name = "aciterraformserver"
version = "0.1.0"
description = ""
authors = ["Antony <47122295+atxit@users.noreply.github.com.>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
